CREATE DATABASE gestao_produtos;

USE gestao_produtos;

CREATE TABLE produtos (
id_produto INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(255),
descrição VARCHAR(255),
categoria VARCHAR(255),
preco DECIMAL(10,2),
peso DECIMAL(10,3),
quantidade INT,
fornecedor INT,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletado_em TIMESTAMP NULL
);

CREATE TABLE fornecedores (
id_fornecedor INT PRIMARY KEY AUTO_INCREMENT,
razao_social VARCHAR(255),
cnpj VARCHAR(20),
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletado_em TIMESTAMP NULL
);
